version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building the backend Docker image...
      - docker build -t my-backend -f backend/Dockerfile .
      - docker tag my-backend:latest <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-backend:latest
      - echo Building the frontend Docker image...
      - docker build -t my-frontend -f frontend/Dockerfile .
      - docker tag my-frontend:latest <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-frontend:latest
  post_build:
    commands:
      - echo Pushing the backend Docker image to ECR...
      - docker push <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-backend:latest
      - echo Pushing the frontend Docker image to ECR...
      - docker push <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-frontend:latest
      - echo Creating imagedefinitions.json file...
      - printf '[{"name":"my-backend","imageUri":"%s"},{"name":"my-frontend","imageUri":"%s"}]' <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-backend:latest <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-frontend:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
