version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 381492175992.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building the backend Docker image...
      - cd api
      - docker build -t lms-backend .
      - docker tag lms-backend:latest 381492175992.dkr.ecr.us-west-2.amazonaws.com/lms-backend:latest
      - echo Building the frontend Docker image...
      - cd webapp
      - docker build -t lms-frontend .
      - docker tag lms-frontend:latest 381492175992.dkr.ecr.us-west-2.amazonaws.com/lms-frontend:latest
  post_build:
    commands:
      - echo Pushing the backend Docker image to ECR...
      - docker push 381492175992.dkr.ecr.us-west-2.amazonaws.com/lms-backend:latest
      - echo Pushing the frontend Docker image to ECR...
      - docker push 381492175992.dkr.ecr.us-west-2.amazonaws.com/lms-frontend:latest
      - echo Creating imagedefinitions.json file...
      - printf '[{"name":"my-backend","imageUri":"%s"},{"name":"my-frontend","imageUri":"%s"}]' 381492175992.dkr.ecr.us-west-2.amazonaws.com/lms-backend:latest 381492175992.dkr.ecr.us-west-2.amazonaws.com/lms-frontend:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
